name: Anne Sophie Grac
email: annesophiegrac@gmail.com
portrait: /img/uploads/portrait-anneso-5.jpg
headline: Anne Sophie Grac est scénographe et costumière.
subheadline: Formée à l'École du Théâtre National de Strasbourg, elle conçoit depuis 12 ans des dispositifs scéniques et des costumes pour le Théâtre et l'Opéra. La richesse et la diversité de ses collaborations ont nourri son regard du plateau, donnant naissance à des espaces inventifs, pensés comme de véritables partenaires de jeu pour les interprètes.
